import type { IpaPhoneme } from '@lab/shared';
import { activity, choice, plain, say } from '../build';
import type { CatalogUnit } from '../types';

/** The 44 phonemes of British English (RP), with the sound bracketed in
 * each example word. */
export const PHONEMES: IpaPhoneme[] = [
  { symbol: 'ɪ', group: 'short-vowel', examples: ['sh[i]p', 's[i]t', 'b[i]g'], tip: 'Short and relaxed — shorter than the vowel in "sheep".' },
  { symbol: 'e', group: 'short-vowel', examples: ['b[e]d', 'p[e]n', 'h[ea]d'] },
  { symbol: 'æ', group: 'short-vowel', examples: ['c[a]t', 'h[a]t', 'bl[a]ck'], tip: 'Open your mouth wider than for /e/.' },
  { symbol: 'ʌ', group: 'short-vowel', examples: ['c[u]p', 'l[o]ve', 's[u]n'] },
  { symbol: 'ɒ', group: 'short-vowel', examples: ['h[o]t', 'd[o]g', 'w[a]tch'], tip: 'Short, with slightly rounded lips.' },
  { symbol: 'ʊ', group: 'short-vowel', examples: ['b[oo]k', 'p[u]t', 'c[ou]ld'] },
  { symbol: 'ə', group: 'short-vowel', examples: ['[a]bout', 'teach[er]', 'sof[a]'], tip: 'The schwa — the most common sound in English, used in almost every unstressed syllable.' },
  { symbol: 'iː', group: 'long-vowel', examples: ['sh[ee]p', 's[ea]', 'k[ey]'], tip: 'Long, with spread lips — smile.' },
  { symbol: 'ɑː', group: 'long-vowel', examples: ['c[ar]', 'f[a]ther', 'h[ear]t'] },
  { symbol: 'ɔː', group: 'long-vowel', examples: ['d[oor]', 'w[al]k', 's[aw]'] },
  { symbol: 'uː', group: 'long-vowel', examples: ['bl[ue]', 'f[oo]d', 't[wo]'] },
  { symbol: 'ɜː', group: 'long-vowel', examples: ['b[ir]d', 'w[or]d', 'l[ear]n'], tip: 'No /r/ sound in British English — hold the vowel.' },
  { symbol: 'eɪ', group: 'diphthong', examples: ['d[ay]', 'r[ai]n', 'm[a]ke'] },
  { symbol: 'aɪ', group: 'diphthong', examples: ['m[y]', 't[i]me', 'h[igh]'] },
  { symbol: 'ɔɪ', group: 'diphthong', examples: ['b[oy]', 'c[oi]n', 'n[oi]se'] },
  { symbol: 'aʊ', group: 'diphthong', examples: ['n[ow]', 'h[ou]se', 'c[ow]'] },
  { symbol: 'əʊ', group: 'diphthong', examples: ['g[o]', 'h[o]me', 'b[oa]t'] },
  { symbol: 'ɪə', group: 'diphthong', examples: ['h[ere]', 'n[ear]', 'id[ea]'] },
  { symbol: 'eə', group: 'diphthong', examples: ['h[air]', 'wh[ere]', 'c[are]'] },
  { symbol: 'ʊə', group: 'diphthong', examples: ['t[our]', 'p[ure]', 'c[ure]'] },
  { symbol: 'p', group: 'consonant', voiced: false, examples: ['[p]en', 'ha[pp]y', 'sto[p]'], tip: 'A puff of air — hold paper in front of your mouth and it moves.' },
  { symbol: 'b', group: 'consonant', voiced: true, examples: ['[b]ag', 'ra[bb]it', 'jo[b]'] },
  { symbol: 't', group: 'consonant', voiced: false, examples: ['[t]ea', 'be[tt]er', 'ca[t]'] },
  { symbol: 'd', group: 'consonant', voiced: true, examples: ['[d]og', 'la[dd]er', 'ba[d]'] },
  { symbol: 'k', group: 'consonant', voiced: false, examples: ['[c]at', '[k]ey', 'ba[ck]'] },
  { symbol: 'ɡ', group: 'consonant', voiced: true, examples: ['[g]o', 'bi[gg]er', 'ba[g]'] },
  { symbol: 'f', group: 'consonant', voiced: false, examples: ['[f]ish', '[ph]one', 'lau[gh]'] },
  { symbol: 'v', group: 'consonant', voiced: true, examples: ['[v]an', 'se[v]en', 'lo[v]e'], tip: 'Top teeth on the bottom lip — not /w/.' },
  { symbol: 'θ', group: 'consonant', voiced: false, examples: ['[th]ink', 'ba[th]', 'mou[th]'], tip: 'Tongue between the teeth, blow — no voice.' },
  { symbol: 'ð', group: 'consonant', voiced: true, examples: ['[th]is', 'mo[th]er', 'brea[th]e'], tip: 'Tongue between the teeth, with voice.' },
  { symbol: 's', group: 'consonant', voiced: false, examples: ['[s]un', 'ki[ss]', 'ri[c]e'] },
  { symbol: 'z', group: 'consonant', voiced: true, examples: ['[z]oo', 'ea[s]y', 'ri[s]e'] },
  { symbol: 'ʃ', group: 'consonant', voiced: false, examples: ['[sh]oe', 'na[t]ion', 'wa[sh]'] },
  { symbol: 'ʒ', group: 'consonant', voiced: true, examples: ['vi[s]ion', 'mea[s]ure', 'u[s]ual'] },
  { symbol: 'h', group: 'consonant', voiced: false, examples: ['[h]at', '[wh]o', 'be[h]ind'] },
  { symbol: 'tʃ', group: 'consonant', voiced: false, examples: ['[ch]air', 'na[t]ure', 'wa[tch]'] },
  { symbol: 'dʒ', group: 'consonant', voiced: true, examples: ['[j]am', 'a[g]e', 'bri[dge]'] },
  { symbol: 'm', group: 'consonant', voiced: true, examples: ['[m]an', 'su[mm]er', 'ti[m]e'] },
  { symbol: 'n', group: 'consonant', voiced: true, examples: ['[n]ose', 'di[nn]er', 'su[n]'] },
  { symbol: 'ŋ', group: 'consonant', voiced: true, examples: ['si[ng]', 'thi[n]k', 'lo[ng]'], tip: 'Back of the tongue up — do not add a /g/ at the end.' },
  { symbol: 'l', group: 'consonant', voiced: true, examples: ['[l]ight', 'ye[ll]ow', 'fee[l]'] },
  { symbol: 'r', group: 'consonant', voiced: true, examples: ['[r]ed', 'so[rr]y', 'w[r]ong'], tip: 'Only pronounced before a vowel in British English.' },
  { symbol: 'w', group: 'consonant', voiced: true, examples: ['[w]et', 'q[u]een', 'a[w]ay'], tip: 'Round your lips — not /v/.' },
  { symbol: 'j', group: 'consonant', voiced: true, examples: ['[y]es', '[u]se', 'b[e]auty'] },
];

// [word, transcription, the sound asked about, distractor symbols]
const VOWEL_QUIZ: Array<[string, string, string, string[]]> = [
  ['ship', 'ʃɪp', 'ɪ', ['iː', 'e']],
  ['sheep', 'ʃiːp', 'iː', ['ɪ', 'eɪ']],
  ['bed', 'bed', 'e', ['æ', 'ɪ']],
  ['bad', 'bæd', 'æ', ['e', 'ʌ']],
  ['cup', 'kʌp', 'ʌ', ['ɒ', 'æ']],
  ['cop', 'kɒp', 'ɒ', ['ʌ', 'ɔː']],
  ['book', 'bʊk', 'ʊ', ['uː', 'ʌ']],
  ['food', 'fuːd', 'uː', ['ʊ', 'əʊ']],
  ['bird', 'bɜːd', 'ɜː', ['ɑː', 'ɔː']],
  ['card', 'kɑːd', 'ɑː', ['ɜː', 'æ']],
  ['cord', 'kɔːd', 'ɔː', ['ɒ', 'əʊ']],
  ['day', 'deɪ', 'eɪ', ['e', 'aɪ']],
  ['time', 'taɪm', 'aɪ', ['eɪ', 'ɔɪ']],
  ['boy', 'bɔɪ', 'ɔɪ', ['aɪ', 'əʊ']],
  ['house', 'haʊs', 'aʊ', ['əʊ', 'ɔː']],
  ['home', 'həʊm', 'əʊ', ['aʊ', 'ɒ']],
  ['near', 'nɪə', 'ɪə', ['eə', 'iː']],
  ['hair', 'heə', 'eə', ['ɪə', 'ɜː']],
  ['tour', 'tʊə', 'ʊə', ['ɔː', 'əʊ']],
  ['love', 'lʌv', 'ʌ', ['ɒ', 'əʊ']],
  ['walk', 'wɔːk', 'ɔː', ['ɒ', 'əʊ']],
  ['learn', 'lɜːn', 'ɜː', ['e', 'ɑː']],
  ['heart', 'hɑːt', 'ɑː', ['ɜː', 'ʌ']],
  ['key', 'kiː', 'iː', ['eɪ', 'ɪ']],
  ['put', 'pʊt', 'ʊ', ['ʌ', 'uː']],
  ['rain', 'reɪn', 'eɪ', ['e', 'aɪ']],
  ['high', 'haɪ', 'aɪ', ['eɪ', 'ɪə']],
  ['coin', 'kɔɪn', 'ɔɪ', ['aɪ', 'ɔː']],
  ['watch', 'wɒtʃ', 'ɒ', ['ɔː', 'æ']],
  ['head', 'hed', 'e', ['iː', 'æ']],
];

// [word, transcription, sound, where it is, distractor symbols]
const CONSONANT_QUIZ: Array<[string, string, string, 'begins' | 'ends' | 'is in the middle of', string[]]> = [
  ['think', 'θɪŋk', 'θ', 'begins', ['ð', 's', 't']],
  ['this', 'ðɪs', 'ð', 'begins', ['θ', 'd', 'z']],
  ['shoe', 'ʃuː', 'ʃ', 'begins', ['s', 'tʃ', 'ʒ']],
  ['chair', 'tʃeə', 'tʃ', 'begins', ['ʃ', 'dʒ', 't']],
  ['jam', 'dʒæm', 'dʒ', 'begins', ['ʒ', 'j', 'tʃ']],
  ['yes', 'jes', 'j', 'begins', ['dʒ', 'w']],
  ['van', 'væn', 'v', 'begins', ['w', 'f', 'b']],
  ['wet', 'wet', 'w', 'begins', ['v', 'r']],
  ['zoo', 'zuː', 'z', 'begins', ['s', 'ʒ']],
  ['hat', 'hæt', 'h', 'begins', ['f', 'k']],
  ['red', 'red', 'r', 'begins', ['l', 'w']],
  ['light', 'laɪt', 'l', 'begins', ['r', 'n']],
  ['pen', 'pen', 'p', 'begins', ['b', 'f']],
  ['bag', 'bæɡ', 'b', 'begins', ['p', 'v']],
  ['go', 'ɡəʊ', 'ɡ', 'begins', ['k', 'dʒ']],
  ['sing', 'sɪŋ', 'ŋ', 'ends', ['n', 'ɡ']],
  ['sun', 'sʌn', 'n', 'ends', ['ŋ', 'm']],
  ['measure', 'meʒə', 'ʒ', 'is in the middle of', ['ʃ', 'dʒ', 'z']],
  ['bath', 'bɑːθ', 'θ', 'ends', ['f', 's', 't']],
  ['breathe', 'briːð', 'ð', 'ends', ['θ', 'v', 'z']],
  ['wash', 'wɒʃ', 'ʃ', 'ends', ['tʃ', 's']],
  ['watch', 'wɒtʃ', 'tʃ', 'ends', ['ʃ', 'dʒ']],
  ['bridge', 'brɪdʒ', 'dʒ', 'ends', ['ʒ', 'tʃ', 'ɡ']],
  ['rice', 'raɪs', 's', 'ends', ['z', 'ʃ']],
  ['rise', 'raɪz', 'z', 'ends', ['s', 'ʒ']],
  ['phone', 'fəʊn', 'f', 'begins', ['v', 'p']],
  ['cat', 'kæt', 'k', 'begins', ['ɡ', 'tʃ']],
  ['dog', 'dɒɡ', 'd', 'begins', ['t', 'ð']],
  ['mouth', 'maʊθ', 'θ', 'ends', ['f', 's']],
  ['king', 'kɪŋ', 'ŋ', 'ends', ['n', 'ɡ']],
];

// [transcription, the word, distractor words]
const TRANSCRIPTION_QUIZ: Array<[string, string, string[]]> = [
  ['ʃɪp', 'ship', ['sheep', 'chip']],
  ['tʃiːp', 'cheap', ['sheep', 'chip']],
  ['θɪŋk', 'think', ['sink', 'thing']],
  ['θɪŋ', 'thing', ['think', 'sing']],
  ['wɜːk', 'work', ['walk', 'week']],
  ['wɔːk', 'walk', ['work', 'woke']],
  ['wəʊk', 'woke', ['walk', 'work']],
  ['bɜːd', 'bird', ['board', 'bed']],
  ['bɔːd', 'board', ['bird', 'bad']],
  ['hɑːt', 'heart', ['hat', 'hurt']],
  ['hɜːt', 'hurt', ['heart', 'hat']],
  ['hæt', 'hat', ['hut', 'heart']],
  ['hʌt', 'hut', ['hat', 'hot']],
  ['lʊk', 'look', ['luck', 'Luke']],
  ['luːz', 'lose', ['loose', 'laws']],
  ['luːs', 'loose', ['lose', 'lace']],
  ['vest', 'vest', ['west', 'best']],
  ['west', 'west', ['vest', 'waist']],
  ['jet', 'yet', ['jet', 'get']],
  ['dʒet', 'jet', ['yet', 'chat']],
  ['pleʒə', 'pleasure', ['pressure', 'player']],
  ['preʃə', 'pressure', ['pleasure', 'preacher']],
  ['ðeə', 'there', ['dare', 'tear']],
  ['tʃɔɪs', 'choice', ['joys', 'chose']],
];

export const IPA_UNIT: CatalogUnit = {
  key: 'pron-sounds',
  title: 'The Sounds of English',
  description: 'The International Phonetic Alphabet: every sound of English, its symbol and example words.',
  activities: [
    activity({
      key: 'pron.ipa.chart',
      title: 'Interactive IPA chart',
      kind: 'ipa-chart',
      cefr: 'A1',
      skill: 'pronunciation',
      mode: 'practice',
      intro:
        'English spelling does not always tell you how a word sounds. The International Phonetic Alphabet (IPA) gives every sound its own symbol. Tap a symbol to hear its example words, then say them yourself.',
      phonemes: PHONEMES,
    }),
    activity({
      key: 'pron.ipa.vowels',
      title: 'Vowel sounds quiz',
      kind: 'quiz',
      cefr: 'A2',
      skill: 'pronunciation',
      mode: 'practice',
      intro: 'Listen to each word and choose the vowel sound you hear. The word is shown after you answer.',
      sampleSize: 12,
      items: VOWEL_QUIZ.map(([word, ipa, symbol, others]) =>
        choice('Listen. Which vowel sound do you hear?', `/${symbol}/`, others.map((o) => `/${o}/`), {
          audio: say(word),
          tag: 'ipa.vowels',
          explain: `${word} /${ipa}/`,
        }),
      ),
    }),
    activity({
      key: 'pron.ipa.consonants',
      title: 'Consonant sounds quiz',
      kind: 'quiz',
      cefr: 'A2',
      skill: 'pronunciation',
      mode: 'practice',
      intro: 'Listen to each word and choose the consonant sound you hear.',
      sampleSize: 12,
      items: CONSONANT_QUIZ.map(([word, ipa, symbol, where, others]) =>
        choice(`Listen. Which sound ${where} the word?`, `/${symbol}/`, others.map((o) => `/${o}/`), {
          audio: say(word),
          tag: 'ipa.consonants',
          explain: `${word} /${ipa}/`,
        }),
      ),
    }),
    activity({
      key: 'pron.ipa.transcription',
      title: 'Read the phonetic symbols',
      kind: 'quiz',
      cefr: 'B1',
      skill: 'pronunciation',
      mode: 'practice',
      intro: 'Read each transcription and choose the word it spells. Use the IPA chart if you need help.',
      sampleSize: 12,
      items: TRANSCRIPTION_QUIZ.map(([ipa, word, others]) =>
        choice(`Which word is /${ipa}/?`, word, others, { audio: undefined, tag: 'ipa.transcription', explain: `/${ipa}/ = ${word}` }),
      ),
    }),
  ],
};

/** Every example word of the chart, for the sound-item count. */
export const IPA_EXAMPLE_WORDS = PHONEMES.flatMap((p) => p.examples.map(plain));
