/**
 * The single runtime branch between hosts (design doc §1.4). Electron's
 * preload script (apps/desktop/src/preload) sets window.__LAB__ via
 * contextBridge before apps/web's code ever runs; the browser gets an
 * equivalent object from a build-time fallback (runtime-config.ts).
 * Shared here so desktop's preload and web's runtime-config never drift
 * against each other again — they did once already (caught during this
 * build: desktop's own copy of this interface was missing the fields
 * web's side had already added).
 */
export interface LabRuntimeConfig {
  platform: 'web' | 'desktop';
  serverUrl: string;
  stationId?: string;
  /** Set by Electron's preload from the main process's persisted
   * machineGuid (apps/desktop/src/main/station-identity.ts) — NOT
   * generated by the preload itself (async file read, no top-level
   * await in a CJS build); passed down via webPreferences.additionalArguments.
   * Absent in a plain browser, where getOrCreateBrowserMachineGuid()
   * mints one into localStorage instead (dev/test path only — design
   * doc §3.7: real stations are Electron-only). */
  machineGuid?: string;
  /** The PC's real name (os.hostname() in Electron's main process), so the
   * renderer's station:hello doesn't overwrite it on the Station row with a
   * browser-xxxx placeholder. Absent in a plain browser, which can't read it. */
  hostname?: string;
  /** LiveKit's own WS endpoint — deliberately NOT derived from serverUrl
   * (different services, no fixed port relationship in a real
   * deployment). TODO(Phase 1 hardening): serve this from the API
   * instead of a build-time/argv fallback. */
  livekitUrl?: string;
}
