import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { batchesApi } from '../../lib/batches-api';
import { queryKeys } from '../../lib/query-keys';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { CopyButton } from '@/components/ui/copy-button';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';

// Same floors as zBatchCode / zBatchJoinKey — only enforced when the field
// is filled in, since a blank one is generated by the server.
const MIN_CODE = 3;
const MIN_KEY = 6;

/**
 * The teacher's own classes (GET /batches/mine — the ones they teach) and the
 * place to make a new one. A teacher creates a class without an admin: name
 * is the only required field, and a blank code or join key is generated by
 * the server (BatchesService.createForTeacher). The creator is linked to the
 * class as its teacher in the same write.
 *
 * Teachers-only in the router and sidebar: an ADMIN creates classes on the
 * Batches page, where code and key are explicit.
 */
export function MyClassesPage() {
  const queryClient = useQueryClient();
  const { data: classes, isLoading } = useQuery({ queryKey: queryKeys.myClasses, queryFn: batchesApi.mine });

  const [open, setOpen] = useState(false);
  const [name, setName] = useState('');
  const [code, setCode] = useState('');
  const [joinKey, setJoinKey] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [created, setCreated] = useState<{ name: string; code: string; joinKey: string } | null>(null);

  function closeDialog(): void {
    setOpen(false);
    setName('');
    setCode('');
    setJoinKey('');
    setError(null);
    setCreated(null);
  }

  const create = useMutation({
    mutationFn: () =>
      batchesApi.createClassroom({
        name: name.trim(),
        ...(code.trim() ? { code: code.trim() } : {}),
        ...(joinKey.trim() ? { joinKey: joinKey.trim() } : {}),
      }),
    onSuccess: (row) => {
      setCreated({ name: row.name, code: row.code, joinKey: row.joinKey ?? '' });
      setError(null);
      void queryClient.invalidateQueries({ queryKey: queryKeys.myClasses });
      // The Sessions page's class picker reads this list too.
      void queryClient.invalidateQueries({ queryKey: queryKeys.batches });
    },
    onError: (err) => setError(err instanceof Error ? err.message : 'Failed to create class'),
  });

  const codeTooShort = code.trim() !== '' && code.trim().length < MIN_CODE;
  const keyTooShort = joinKey.trim() !== '' && joinKey.trim().length < MIN_KEY;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-semibold">My classes</h1>
          <p className="text-sm text-muted-foreground">Create a class, share its code and key, and manage who is in it.</p>
        </div>
        <Dialog open={open} onOpenChange={(v) => (v ? setOpen(true) : closeDialog())}>
          <DialogTrigger asChild>
            <Button>Create class</Button>
          </DialogTrigger>
          <DialogContent>
            {created ? (
              <>
                <DialogHeader>
                  <DialogTitle>{created.name} is ready</DialogTitle>
                </DialogHeader>
                <p className="text-sm text-muted-foreground">Give students the class code and join key. They enter both from their My classes screen.</p>
                <div className="space-y-2 rounded-md border p-3">
                  <div className="flex items-center gap-2">
                    <span className="w-20 text-xs text-muted-foreground">Class code</span>
                    <span className="font-mono text-sm">{created.code}</span>
                    <CopyButton value={created.code} label="class code" />
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="w-20 text-xs text-muted-foreground">Join key</span>
                    <span className="font-mono text-sm">{created.joinKey}</span>
                    <CopyButton value={created.joinKey} label="join key" />
                  </div>
                </div>
                <DialogFooter>
                  <Button onClick={closeDialog}>Done</Button>
                </DialogFooter>
              </>
            ) : (
              <>
                <DialogHeader>
                  <DialogTitle>Create class</DialogTitle>
                </DialogHeader>
                <div className="space-y-3">
                  <div className="space-y-1.5">
                    <Label htmlFor="class-name">Name</Label>
                    <Input id="class-name" value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Morning English" />
                  </div>
                  <div className="space-y-1.5">
                    <Label htmlFor="class-code">Class code</Label>
                    <Input id="class-code" value={code} onChange={(e) => setCode(e.target.value)} placeholder="Leave blank to auto-generate" />
                    {codeTooShort && <p className="text-xs text-destructive">At least {MIN_CODE} characters.</p>}
                  </div>
                  <div className="space-y-1.5">
                    <Label htmlFor="class-key">Join key</Label>
                    <Input id="class-key" value={joinKey} onChange={(e) => setJoinKey(e.target.value)} placeholder="Leave blank to auto-generate" />
                    {keyTooShort && <p className="text-xs text-destructive">At least {MIN_KEY} characters.</p>}
                  </div>
                  {error && <p className="text-sm text-destructive">{error}</p>}
                </div>
                <DialogFooter>
                  <Button onClick={() => create.mutate()} disabled={create.isPending || !name.trim() || codeTooShort || keyTooShort}>
                    {create.isPending ? 'Creating…' : 'Create'}
                  </Button>
                </DialogFooter>
              </>
            )}
          </DialogContent>
        </Dialog>
      </div>

      {isLoading && <p className="text-sm text-muted-foreground">Loading…</p>}

      {classes?.length === 0 && (
        <div className="rounded-md border border-dashed p-6 text-center">
          <p className="text-sm font-medium">You don't teach any classes yet.</p>
          <p className="text-sm text-muted-foreground">Create one to get a class code and join key to share with your students.</p>
        </div>
      )}

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
        {classes?.map((c) => (
          <Card key={c.id}>
            <CardHeader className="flex-row items-start justify-between gap-2 space-y-0">
              <CardTitle className="text-base">
                <Link to={`/classes/${c.id}`} className="text-primary hover:underline">
                  {c.name}
                </Link>
              </CardTitle>
              {/* Joining can be opened/closed from the class page ("Accept new students"). */}
              <Link
                to={`/classes/${c.id}`}
                title={c.joinOpen ? 'Open — students can join with the code and key.' : 'Closed — students cannot join.'}
                className="rounded-md outline-none focus-visible:ring-2 focus-visible:ring-ring"
              >
                <Badge variant={c.joinOpen ? 'success' : 'secondary'} className="cursor-pointer hover:opacity-80">
                  {c.joinOpen ? 'Open' : 'Closed'}
                </Badge>
              </Link>
            </CardHeader>
            <CardContent className="space-y-1 text-sm">
              <div className="flex items-center gap-1.5">
                <span className="font-mono text-xs">{c.code}</span>
                <CopyButton value={c.code} label="class code" />
              </div>
              <p className="text-muted-foreground">
                {c.studentCount} {c.studentCount === 1 ? 'student' : 'students'}
              </p>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
