/** Centralized TanStack Query keys — Phase 1/2 inlined array literals
 * per call site and had already duplicated one key by the time Phase 3
 * started (['stations','status-board'] in two files); this is the fix. */
export const queryKeys = {
  stationsStatusBoard: ['stations', 'status-board'] as const,
  batches: ['batches'] as const,
  sessions: ['sessions'] as const,
  /** One class's sessions, or every session the caller may see. */
  sessionsList: (batchId?: string) => ['sessions', 'list', batchId ?? 'all'] as const,
  roundTable: (sessionId: string) => ['round-table', sessionId] as const,
  roundTableReview: (sessionId: string, groupId: string) => ['round-table', sessionId, groupId, 'review'] as const,
  adminBatches: ['admin', 'batches'] as const,
  adminBatch: (id: string) => ['admin', 'batches', id] as const,
  adminBatchStudents: (id: string) => ['admin', 'batches', id, 'students'] as const,
  users: (role?: string) => ['users', role ?? 'all'] as const,
  myEnrollments: ['my-enrollments'] as const,
  myClasses: ['my-classes'] as const,
  classStudents: (id: string) => ['my-classes', id, 'students'] as const,
  mediaAssets: ['media-assets'] as const,
  mediaFolders: ['media-folders'] as const,
  mediaAsset: (id: string) => ['media-assets', id] as const,
  contentPackages: ['content-packages'] as const,
  exercises: ['exercises'] as const,
  exercise: (id: string) => ['exercises', id] as const,
  exerciseItems: (id: string) => ['exercises', id, 'items'] as const,
  gradebookAttempts: (filter: Record<string, string | undefined>) => ['gradebook', 'attempts', filter] as const,
  gradebookAttempt: (id: string) => ['gradebook', 'attempts', id] as const,
  gradebookAssignments: (filter: Record<string, string | undefined>) => ['gradebook', 'assignments', filter] as const,
  pronunciationStatus: ['pronunciation', 'status'] as const,
  pronunciationExercises: ['pronunciation', 'exercises'] as const,
  pronunciationAttempts: (exerciseId: string) => ['pronunciation', 'attempts', exerciseId] as const,
  pronunciationTests: ['pronunciation', 'tests'] as const,
  pronunciationTest: (id: string) => ['pronunciation', 'tests', id] as const,
  assessments: (type: string) => ['assessments', 'list', type] as const,
  assessment: (id: string) => ['assessments', 'detail', id] as const,
  studyModules: ['study-modules'] as const,
  translationLanguages: ['translation', 'languages'] as const,
  translationSettings: ['translation', 'settings'] as const,
  translationHealth: ['translation', 'health'] as const,
  translationClassStatus: (classId: string) => ['translation', 'class', classId] as const,
  translationTestRuns: ['translation', 'test-runs'] as const,
  translationTestRun: (id: string) => ['translation', 'test-runs', id] as const,
  studentAssignments: ['student', 'assignments'] as const,
  studentStudyLibrary: ['student', 'study-library'] as const,
  /** A student's record of one class (My Classes -> open a class). */
  classHistory: (batchId: string) => ['class-history', batchId] as const,
  classHistoryAll: ['class-history'] as const,
  dictionaryTopWords: (days: number) => ['dictionary', 'top-words', days] as const,
  classRecordings: ['class-recordings'] as const,
};
